name: "Una Kravets' Portfolio"
description: "The online portflio of Una Kravets, front end developer and graphic designer based in Washington, DC."

url: "unakravets.com"

permalink: pretty
pygments: true

auto: true
