name: "Una Kravets' Portfolio"
description: "The online portflio of Una Kravets, front end developer and graphic designer based in Washington, DC."

url: "[YOUR DOMAIN]"

markdown: rdiscount
rdiscount extensions: [smart]

permalink: pretty
pygments: true

auto: true
